micronaut:
  application:
    name: demo
  server:
    cors:
      enabled: true
      configurations:
        all:
          allowed-origins:
            - "http://localhost:4200"
            - "https://d15dzv70fdtos7.cloudfront.net"
          allowed-methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          allowed-headers:
            - "*"
          allow-credentials: true
          max-age: 3600
    port: 8080
  serde:
    serialization:
      inclusion: ALWAYS
  security:
    authentication: bearer
    token:
      roles-name: "cognito:groups"
      name-key: "sub"
      jwt:
        signatures:
          jwks:
            awscognito:
              url: 'https://cognito-idp.us-east-1.amazonaws.com/us-east-1_BE7MaqC5T/.well-known/jwks.json'

endpoints:
  beans:
    enabled: false
  info:
    enabled: false
  loggers:
    enabled: false
  metrics:
    enabled: false
  refresh:
    enabled: false
  routes:
    enabled: false
  threaddump:
    enabled: false
  env:
    enabled: false
  caches:
    enabled: false
  stop:
    enabled: false

mongodb:
  uri: ${MONGODB_URI}
