micronaut:
  application:
    name: demo
  server:
    cors:
      enabled: true
    port: 8080
  serde:
    serialization:
      inclusion: ALWAYS

pagination:
  default-count: 10

mongodb:
  uri: ${MONGODB_URI}
