micronaut:
  application:
    name: demo
  server:
    cors:
      enabled: true
      configurations:
        all:
          allowed-origins:
            - "http://localhost:4200"
            - "https://d15dzv70fdtos7.cloudfront.net"
          allowed-methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          allowed-headers:
            - "*"
          allow-credentials: true
          max-age: 3600
    port: 8080
  serde:
    serialization:
      inclusion: ALWAYS
  # Security temporarily disabled for testing
  # security:
  #   authentication: bearer
  #   intercept-url-map:
  #     - pattern: /health
  #       access:
  #         - isAnonymous()
  #     - pattern: /info
  #       access:
  #         - isAnonymous()
  #   token:
  #     roles-name: "cognito:groups"
  #     name-key: "sub"
  #     jwt:
  #       signatures:
  #         jwks:
  #           awscognito:
  #             url: 'https://cognito-idp.us-east-1.amazonaws.com/us-east-1_BE7MaqC5T/.well-known/jwks.json'

endpoints:
  all:
    enabled: false
    sensitive: false
  health:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false

mongodb:
  servers:
    - host: ${DATABASE_URL:localhost}
      port: 27017
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  database: ${DB_NAME:appointments}
  ssl:
    enabled: ${SSL_ENABLED:false}
  options:
    replicaSet: rs0
    readPreference: secondaryPreferred
    retryWrites: false
  